# Generated by Django 2.1.7 on 2019-03-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to',
            name='action',
            field=models.CharField(choices=[('doing', 'doing'), ('done', 'done'), ('cancer', 'cancer')], default='doing', max_length=20),
        ),
    ]
